#!/usr/bin/env python
"""Regenerate examples/*/README.md and examples/README.md from the examples.

Each example's first markdown cell already carries a title and a summary. That
is the single source of truth: these READMEs are derived from it so the two
cannot drift. tests/test_examples.py regenerates them in memory and fails if
the files on disk differ, so a stale README is a test failure rather than a
thing a reader discovers.

Usage:
    python tools/sync_example_docs.py          # rewrite the files
    python tools/sync_example_docs.py --check  # exit 1 if anything is stale
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
VIEWER_CALLS = ("show_structure", "animate_trajectory", "animate_mode")


def example_paths():
    """Every examples/<name>/<name>.py, sorted by name."""
    return sorted(
        d / f"{d.name}.py" for d in EXAMPLES.iterdir()
        if d.is_dir() and (d / f"{d.name}.py").exists()
    )


def parse_header(path: pathlib.Path) -> tuple[str, str]:
    """Return (title, summary) from the example's first markdown cell."""
    text = path.read_text()
    match = re.search(r"# %% \[markdown\]\n((?:#.*\n)+)", text)
    if not match:
        raise ValueError(f"{path} has no leading markdown cell")

    lines = [line[2:] if line.startswith("# ") else line[1:]
             for line in match.group(1).splitlines()]
    lines = [line.rstrip() for line in lines]

    title = next((l[2:].strip() for l in lines if l.startswith("# ")), None)
    if title is None:
        raise ValueError(f"{path} markdown cell has no '# Title' line")

    body = [l for l in lines if l.strip() and not l.startswith("#")]
    return title, "\n".join(body).strip()


def needs_py3dmol(path: pathlib.Path) -> bool:
    """Whether the example calls a py3Dmol-backed viewer."""
    text = path.read_text()
    return any(call in text for call in VIEWER_CALLS)


def render_readme(path: pathlib.Path) -> str:
    """Build the per-example README."""
    name = path.stem
    title, summary = parse_header(path)

    extra = ""
    if needs_py3dmol(path):
        extra = (
            "\nThis example uses the 3D viewers in `jaxmm.notebook`, so it needs "
            "`py3Dmol`:\n\n```bash\npip install -e \".[examples]\"\n```\n"
        )

    return f"""<!-- Generated by tools/sync_example_docs.py. Do not edit by hand. -->
# {title}

{summary}

## Run

```bash
python examples/{name}/{name}.py
```

This is jupytext "percent" Python, so `# %%` marks a cell. With jupytext
installed you can open it as a notebook directly, or convert it:

```bash
jupytext --to ipynb examples/{name}/{name}.py
```

## Figures

`plt.show()` is a no-op on a headless machine, so nothing is written by
default. To save the figures to `output/` (gitignored):

```bash
python tools/render_examples.py --only {name}
```
{extra}"""


def render_index(paths) -> str:
    """Build the examples/README.md index."""
    rows = []
    for path in paths:
        title, summary = parse_header(path)
        first = summary.split("\n")[0]
        first = re.sub(r"\*\*(.+?)\*\*", r"\1", first)
        first = re.sub(r"`(.+?)`", r"\1", first)
        if len(first) > 96:
            first = first[:93].rsplit(" ", 1)[0] + "..."
        marker = " (needs py3Dmol)" if needs_py3dmol(path) else ""
        rows.append(f"| [{path.stem}]({path.stem}/) | {title}{marker} | {first} |")

    table = "\n".join(rows)
    return f"""<!-- Generated by tools/sync_example_docs.py. Do not edit by hand. -->
# Examples

Each example is a self-contained folder: a jupytext "percent" Python script, a
README, and a gitignored `output/` for figures.

| Example | Title | What it shows |
|---------|-------|---------------|
{table}

## Running

```bash
pip install -e ".[examples]"                     # matplotlib, py3Dmol, jupytext
python examples/quickstart/quickstart.py         # run one
python tools/render_examples.py                  # run all, save figures
python tools/render_examples.py --only quickstart
```

Figures land in each example's `output/`, which is gitignored. Most examples
finish in under a minute, but `free_energy` and `parallel_tempering` run long
MD and take several minutes each; raise `--timeout` if the renderer gives up on
them.

These are plain Python, not notebooks. `# %%` marks a cell, so Jupyter and VS
Code open them as notebooks when jupytext is installed, and they also run as
ordinary scripts. Notebooks are deliberately not committed: stored outputs are
base64 blobs that bloat the repository and produce diffs nobody can review.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if any generated file is stale")
    args = parser.parse_args()

    paths = example_paths()
    if not paths:
        print("no examples found", file=sys.stderr)
        return 1

    wanted = {path.parent / "README.md": render_readme(path) for path in paths}
    wanted[EXAMPLES / "README.md"] = render_index(paths)

    stale = [p for p, text in wanted.items()
             if not p.exists() or p.read_text() != text]

    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("run: python tools/sync_example_docs.py", file=sys.stderr)
        return 1 if stale else 0

    for path, text in wanted.items():
        path.write_text(text)
    print(f"wrote {len(wanted)} files ({len(stale)} were stale)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
